package MovieTicketApp;


/**
* MovieTicketApp/IMovieTicketHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MovieTicket.idl
* Tuesday, 7 February, 2023 4:24:08 PM EST
*/

abstract public class IMovieTicketHelper
{
  private static String  _id = "IDL:MovieTicketApp/IMovieTicket:1.0";

  public static void insert (org.omg.CORBA.Any a, MovieTicketApp.IMovieTicket that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static MovieTicketApp.IMovieTicket extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (MovieTicketApp.IMovieTicketHelper.id (), "IMovieTicket");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static MovieTicketApp.IMovieTicket read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_IMovieTicketStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, MovieTicketApp.IMovieTicket value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static MovieTicketApp.IMovieTicket narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof MovieTicketApp.IMovieTicket)
      return (MovieTicketApp.IMovieTicket)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      MovieTicketApp._IMovieTicketStub stub = new MovieTicketApp._IMovieTicketStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static MovieTicketApp.IMovieTicket unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof MovieTicketApp.IMovieTicket)
      return (MovieTicketApp.IMovieTicket)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      MovieTicketApp._IMovieTicketStub stub = new MovieTicketApp._IMovieTicketStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
