package MovieTicketApp;


/**
* MovieTicketApp/IMovieTicket.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MovieTicket.idl
* Monday, 6 February, 2023 11:09:09 PM EST
*/

public interface IMovieTicket extends IMovieTicketOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IMovieTicket
