module MovieTicketApp {
     interface IMovieTicket {
        /**
         * Permission Set - Admin Only.
         * This method add movie for particular movie if exist in hash map
         * and if the movie does not exist it will create a new movie entry.
         * @param movieId
         * @param movieName
         * @param bookingCapacity
         * @return string If operation successful or not
         */
        string addMovieSlots(in string movieId,in string movieName,in long bookingCapacity);

        /**
         * Permission Set - Admin Only.
         * This method removes the movie if existed.
         * If movie show exist and customer has booked a ticket then
         * movie gets deleted and will book the same movie in next available slot for that customer.
         * @param movieId
         * @param movieName
         * @return string If operation successful or not
         */
        string removeMovieSlots(in string movieId,in string movieName);

        /**
         * Permission Set - Admin Only.
         * This method shows the availability for a particular movie in all theaters.
         * @param movieName
         * @return string If operation successful or not
         */
        string listMovieShowsAvailability(in string movieName);

        /**
         * Permission Set - Admin and User.
         * This method is used tp book movie tickets.
         * @param customerID
         * @param movieId
         * @param movieName
         * @param numberOfTickets
         * @return string If operation successful or not
         */
        string bookMovieTickets(in string customerID,in string movieId,in string movieName,in long numberOfTickets);

        /**
         * Permission Set - Admin and User.
         * This method will get the booking schedule as per customerID from all the different theaters from all area.
         * @param customerID
         * @return string If operation successful or not
         */
        string getBookingSchedule(in string customerID);

        /**
         * Permission Set - Admin and User.
         * This method will allow cancelling of movie ticket with following parameters.
         * @param customerID
         * @param movieID
         * @param movieName
         * @param numberOfTickets
         * @return
         */
        string cancelMovieTickets(in string customerID,in string movieID,in string movieName,in long numberOfTickets);

        string getMoviesListInTheatre(in string movieName);

        string bookTicket(in string customerID,in string movieId,in string movieName,in long numberOfTickets,in boolean isUserRegisteredToServer);

        string getCustomerBookingList(in string customerID);

        string cancelTicket(in string customerID,in string movieID,in string movieName,in long numberOfTickets);

        string exchangeTicket(in string customerID,in string movieID, in string movieName, in string newMovieID, in string newMovieName);
    };
};